var clothes = [
  {
    id: 1,
    name: "diesel",
    price: 100,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1314689_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1314689_5.jpg",
    ],
  },
  {
    id: 2,
    name: "diesel",
    price: 120,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436324_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436324_5.jpg",
    ],
  },
  {
    id: 3,
    name: "diesel",
    price: 110,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436318_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436318_5.jpg",
    ],
  },
  {
    id: 4,
    name: "diesel",
    price: 120,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436317_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436317_5.jpg",
    ],
  },
  {
    id: 5,
    name: "diesel",
    price: 130,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436316_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436316_5.jpg",
    ],
  },
  {
    id: 6,
    name: "diesel",
    price: 190,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436315_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436315_5.jpg",
    ],
  },
  {
    id: 7,
    name: "diesel",
    price: 100,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436314_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436314_5.jpg",
    ],
  },
  {
    id: 8,
    name: "diesel",
    price: 110,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
"https://assetsprx.matchesfashion.com/img/product/1300/1436305_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436305_5.jpg",
    ],
  },
  {
    id: 9,
    name: "diesel",
    price: 130,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436323_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436323_5.jpg",
    ],
  },
  {
    id: 10,
    name: "diesel",
    price: 150,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436321_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436321_5.jpg",
    ],
  },
  {
    id: 11,
    name: "diesel",
    price: 130,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1436306_6.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1436306_5.jpg",
    ],
  },
  {
    id: 12,
    name: "diesel",
    price: 130,
    category: "jeans",
    description: "fashion jeans good quialty for people who love and know fashions jeans",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1436313_6.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1436313_5.jpg",],
  },
  {
    id: 13,
    name: "mike amiri",
    price: 150,
    category: "Tshirt",
    description: "fashion shirt good quialty for people who love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420871_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420871_6.jpg",
    ],
  },
  {
    id: 14,
    name: "mike amiri",
    price: 340,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420868_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420868_6.jpg",
    ],
  },
  {
    id: 15,
    name: "mike amiri",
    price: 370,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420872_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420872_6.jpg",
    ],
  },
  {
    id: 16,
    name: "mike amiri",
    price: 450,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420867_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420867_6.jpg",
    ],
  },
  {
    id: 17,
    name: "mike amiri",
    price: 250,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420870_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420870_6.jpg",
    ],
  },
  {
    id: 18,
    name: "mike amiri",
    price: 275,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420869_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420869_2.jpg",
    ],
  },
  {
    id: 19,
    name: "mike amiri",
    price: 300,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420866_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420866_6.jpg",
    ],
  },
  {
    id: 20,
    name: "mike amiri",
    price: 240,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420894_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420894_4.jpg",
    ],
  },
  {
    id: 21,
    name: "mike amiri",
    price: 190,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420877_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420877_5.jpg",
    ],
  },
  {
    id: 22,
    name: "mike amiri",
    price: 350,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420895_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420895_6.jpg",
    ],
  },
  {
    id: 23,
    name: "mike amiri",
    price: 400,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420896_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420896_6.jpg",
    ],
  },
  {
    id: 24,
    name: "mike amiri",
    price: 390,
    category: "Tshirt",
    description: "fashion shirt good quialty for people how love and know fashions shirt",
    photo: [
      "https://assetsprx.matchesfashion.com/img/product/1300/1420876_1.jpg",
      "https://assetsprx.matchesfashion.com/img/product/1300/1420876_5.jpg",
    ],
  },
  {
    id: 25,
    name: "gucci",
    price: 600,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1416146_1.jpg",
    "https://assetsprx.matchesfashion.com/img/product/1300/1416146_5.jpg",
  ],
  },
  {
    id: 26,
    name: "gucci",
    price: 950,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1223710_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1223710_5.jpg"],
  },
  {
    id: 27,
    name: "gucci",
    price: 390,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1356194_1.jpg",
    "https://assetsprx.matchesfashion.com/img/product/1300/1356194_5.jpg",
  ],
  },
  {
    id: 28,
    name: "gucci",
    price: 670,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1421675_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1421675_5.jpg",],
  },
  {
    id: 29,
    name: "gucci",
    price: 875,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1238474_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1238474_5.jpg",],
  },
  {
    id: 30,
    name: "gucci",
    price: 380,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1431650_1.jpg",
    "https://assetsprx.matchesfashion.com/img/product/1300/1431650_3.jpg"],
  },
  {
    id: 31,
    name: "gucci",
    price: 600,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1284297_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1284297_5.jpg"],
  },
  {
    id: 32,
    name: "gucci",
    price: 550,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1419097_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1419097_4.jpg"],
  },
  {
    id: 33,
    name: "gucci",
    price: 780,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1419096_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1419096_4.jpg"],
  },
  {
    id: 34,
    name: "gucci",
    price: 550,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1419094_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1419094_5.jpg"],
  },
  {
    id: 35,
    name: "gucci",
    price: 400,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1428344_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1428344_5.jpg"],
  },
  {
    id: 36,
    name: "gucci",
    price: 500,
    category: "shoes",
    description: "fashion shoe good quialty for people who love and know fashion",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1266456_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1266456_6.jpg"],
  },
  {
    id: 37,
    name: "tom ford",
    price: 2500,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1435465_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1435465_2.jpg",],
  },
  {
    id: 38,
    name: "tom ford",
    price: 1500,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1426716_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1426716_2.jpg",],
  },
  {
    id: 39,
    name: "tom ford",
    price: 1900,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1277894_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1277894_2.jpg"],
  },
  {
    id: 40,
    name: "tom ford",
    price: 2900,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1435466_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1435466_6.jpg"],
  },
  {
    id: 41,
    name: "tom ford",
    price: 3500,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1276191_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1276191_6.jpg"],
  },
  {
    id: 42,
    name: "tom ford",
    price: 3500,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1311932_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1311932_6.jpg",],
  },
  {
    id: 43,
    name: "tom ford",
    price: 3770,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1311933_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1311933_6.jpg"],
  },
  {
    id: 44,
    name: "tom ford",
    price: 3900,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1397373_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1397373_6.jpg"],
  },
  {
    id: 45,
    name: "tom ford",
    price: 3900,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1311934_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1311934_6.jpg",],
  },
  {
    id: 46,
    name: "tom ford",
    price: 2900,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1419771_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1419771_6.jpg"],
  },
  {
    id: 47,
    name: "tom ford",
    price: 4500,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1389439_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1389439_6.jpg"],
  },
  {
    id: 48,
    name: "tom ford",
    price: 3000,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1239823_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1239823_6.jpg"],
  },
  {
    id: 49,
    name: "tom ford",
    price: 6000,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1311931_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1311931_6.jpg"],
  },
  {
    id: 50,
    name: "tom ford",
    price: 4600,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1239842_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1239842_6.jpg"],
  },
  {
    id: 51,
    name: "tom ford",
    price: 4300,
    description:"fashion suit good quialty for people how love and know fashions suits",
    category: "suits",
    photo: ["https://assetsprx.matchesfashion.com/img/product/1300/1397372_1.jpg",
  "https://assetsprx.matchesfashion.com/img/product/1300/1397372_6.jpg"],
  },
];

